apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: project-app
type: Opaque
stringData:
  DB_USERNAME: "app_user"
  DB_PASSWORD: "secure_db_password_change_me"
  JWT_SECRET: "your_production_jwt_secret_min_32_chars"
  JWT_ACCESS_SECRET: "your_production_jwt_access_secret_min_32_chars"
  JWT_REFRESH_SECRET: "your_production_jwt_refresh_secret_min_32_chars"
  GOOGLE_CLIENT_ID: "your_google_client_id"
  GOOGLE_CLIENT_SECRET: "your_google_client_secret"
