const UserRouter = require("./UserRouter");
const ProductRouter = require("./ProductRouter");
const CategoryRouter = require("./CategoryRouter");
const ReviewRouter = require("./ReviewRouter");
const CartRouter = require("./CartRouter");
const CartItemRouter = require("./CartItemRouter");
const OrderRouter = require("./OrderRouter");
const OrderItemRouter = require("./OrderItemRouter");
const PaymentRouter = require("./PaymentRouter");
const AdminRouter = require("./AdminRouter");
const ChatRouter = require("./ChatRouter");
const VNpayRouter = require("./VNpayRouter");
const ReviewReplyRouter = require("./ReviewReplyRouter");
const BrandRouter = require("./BrandRouter");
const ProductVariantRouter = require("./ProductVariantRouter");
const VoucherRouter = require("./VoucherRouter");
const NotificationRouter = require("./NotificationRouter");
const AddressRouter = require("./AddressRouter");
const WishlistRouter = require("./WishlistRouter");
const AttributeRouter = require("./AttributeRouter");
const SystemSettingRouter = require("./SystemSettingRouter");

const routes = (app) => {
  app.use("/api/v1/user", UserRouter);
  app.use("/api/v1/address", AddressRouter);
  app.use("/api/v1/wishlist", WishlistRouter);
  app.use("/api/v1/product", ProductRouter);
  app.use("/api/v1/attribute", AttributeRouter);
  app.use("/api/v1/brand", BrandRouter);
  app.use("/api/v1/category", CategoryRouter);
  app.use("/api/v1/review", ReviewRouter);
  app.use("/api/v1/review-reply", ReviewReplyRouter);
  app.use("/api/v1/cart", CartRouter);
  app.use("/api/v1/cartItem", CartItemRouter);
  app.use("/api/v1/order", OrderRouter);
  app.use("/api/v1/order-item", OrderItemRouter);
  app.use("/api/v1/payment", PaymentRouter);
  app.use("/api/v1/admin", AdminRouter);
  app.use("/api/v1/chat", ChatRouter);
  app.use("/api/v1/vnpay", VNpayRouter);
  app.use("/api/v1/variant", ProductVariantRouter);
  app.use("/api/v1/voucher", VoucherRouter);
  app.use("/api/v1/notification", NotificationRouter);
  app.use("/api/v1/system-settings", SystemSettingRouter);
};
module.exports = routes;

