const UserRouter = require("./UserRouter");
const ProductRouter = require("./ProductRoutes");
const CategoryRouter = require("./CategoryRouter");
const ReviewRouter = require("./ReviewRouter");
const CartRouter = require("./CartRouter");
const CartItemRouter = require("./CartItemRouter");
const OrderRouter = require("./OrderRouter");
const OrderItemRouter = require("./OrderItemRouter");
const PaymentRouter = require("./PaymentRouter");
const AdminRouter = require("./AdminRoute");
const ChatRoutes = require("./chatRoutes");
const VNpayRoutes = require("./VNpayRouter");
const ReviewReply = require("./ReviewReply");
const BrandRouter = require("./BrandRouter");
const ProductVariantRouter = require("./ProductVariantRouter");
const VoucherRouter = require("./VoucherRouter");
const NotificationRouter = require("./NotificationRouter");
const AddressRouter = require("./AddressRouter");
const WishlistRouter = require("./WishlistRouter");
const AttributeRouter = require("./AttributeRouter");

const routes = (app) => {
  app.use("/api/v1/user", UserRouter);
  app.use("/api/v1/address", AddressRouter);
  app.use("/api/v1/wishlist", WishlistRouter);
  app.use("/api/v1/product", ProductRouter);
  app.use("/api/v1/attribute", AttributeRouter);
  app.use("/api/v1/brand", BrandRouter);
  app.use("/api/v1/category", CategoryRouter);
  app.use("/api/v1/review", ReviewRouter);
  app.use("/api/v1/review-reply", ReviewReply);
  app.use("/api/v1/cart", CartRouter);
  app.use("/api/v1/cartItem", CartItemRouter);
  app.use("/api/v1/order", OrderRouter);
  app.use("/api/v1/order-item", OrderItemRouter);
  app.use("/api/v1/payment", PaymentRouter);
  app.use("/api/v1/admin", AdminRouter);
  app.use("/api/v1/chat", ChatRoutes);
  app.use("/api/v1/vnpay", VNpayRoutes);
  app.use("/api/v1/variant", ProductVariantRouter);
  app.use("/api/v1/voucher", VoucherRouter);
  app.use("/api/v1/notification", NotificationRouter);
};
module.exports = routes;
